package day_2;

public class Bike {
	String color;
	double price;
	int mileage;
	String brand;
	int numberofgears;
	public static void main(String[] args) {
		Bike b1=new Bike();
		b1.color="Grey";
		b1.price=500000;
		b1.mileage=30;
		b1.brand="kawasaki";
		b1.numberofgears=4;
		System.out.println("Color:"+b1.color);
		System.out.println("Price:"+b1.price);
		System.out.println("Mileage:"+b1.mileage);
		System.out.println("Brand:"+b1.brand);
		System.out.println("Numberofgears:"+b1.numberofgears);
		System.out.println("--------------------");
		Bike b2=new Bike();
		b2.color="Black";
		b2.price=1500000;
		b2.mileage=50;
		b2.brand="Hero Honda";
		b2.numberofgears=4;
		System.out.println("Color:"+b2.color);
		System.out.println("Price:"+b2.price);
		System.out.println("Mileage:"+b2.mileage);
		System.out.println("Brand:"+b2.brand);
		System.out.println("Numberofgears:"+b2.numberofgears);
		System.out.println("--------------------");
		Bike b3=new Bike();
		b3.color="White";
		b3.price=50000000;
		b3.mileage=80;
		b3.brand="BMW";
		b3.numberofgears=5;
		System.out.println("Color:"+b3.color);
		System.out.println("Price:"+b3.price);
		System.out.println("Mileage:"+b3.mileage);
		System.out.println("Brand:"+b3.brand);
		System.out.println("Numberofgears:"+b3.numberofgears);
		System.out.println("--------------------");
		Bike b4=new Bike();
		b4.color="Purple";
		b4.price=450000000;
		b4.mileage=50;
		b4.brand="Porsche";
		b4.numberofgears=5;
		System.out.println("Color:"+b4.color);
		System.out.println("Price:"+b4.price);
		System.out.println("Mileage:"+b4.mileage);
		System.out.println("Brand:"+b4.brand);
		System.out.println("Numberofgears:"+b4.numberofgears);
		System.out.println("--------------------");
		Bike b5=new Bike();
		b5.color="Black";
		b5.price=700000000;
		b5.mileage=85;
		b5.brand="Lamborghini";
		b5.numberofgears=5;
		System.out.println("Color:"+b5.color);
		System.out.println("Price:"+b5.price);
		System.out.println("Mileage:"+b5.mileage);
		System.out.println("Brand:"+b5.brand);
		System.out.println("Numberofgears:"+b5.numberofgears);
		System.out.println("--------------------");
	}
}
